#!/usr/bin/bash
path="$1";
list="$(find $path)";
i=0
files=()
uniq_files=()
occ=()
for file in $list; do
	if [[ -f $file ]]; then
		f_n=$(basename $file)
		echo $f_n
		files+=("$f_n");
		if [[ ! "${uniq_files[@]}" =~ "$f_n" ]]; then
			uniq_files+=("$f_n");
		fi
	fi
done
echo  "${files[@]}"
echo  "${uniq_files[@]}"
for uf in ${uniq_files[@]}; do
	for f in ${files[@]}; do
		if  [ $f = $uf ]; then
			(( occ[$i]++ ))
		fi

	done
	let "i++"
done

echo "${occ[@]}"
