#!/usr/bin/bash

find "$1" -type f -exec cat {} + | grep -o '[^ ]\+' | sort | uniq | while read line; do
		echo "$line"
		find "$1" -type f -exec grep -w "$line" {} +
		echo " -----------------"
done
