#!/usr/bin/bash

find "$1" -type f -exec cat {} +| sort | while read line; do
	for word in $line; do
		printf "%s - " "$word"
		find "$1" -type f -exec grep  -wo "$word" {} + |  sort | uniq | wc -l
	done
done | sort | uniq
